name: saegewerk
description: "Schaible SÃ¤gewerk App"
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.10.0-236.0.dev

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0

  # State Management
  provider: ^6.1.2

  package_info_plus: ^9.0.0
  fluttertoast: ^8.2.12
  mobile_scanner: ^7.1.4

  # Storage
  shared_preferences: ^2.2.2

  # UI
  modal_progress_hud_nsn: ^0.5.1
  cupertino_icons: ^1.0.6
  flex_color_picker: ^3.7.1
  # Localization
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/images/welle_1024.png"
    background_color: "#FFFFFF"
    theme_color: "#00897B"
  image_path: "assets/images/welle_1024.png"

  # Android-spezifisch
  adaptive_icon_foreground: "assets/images/welle_1024.png"
  adaptive_icon_background: "#FFFFFF"
  # iOS-spezifisch
  remove_alpha_ios: true


